server:
  port: 8080
  servlet:
    context-path: /api/pm-service

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

keycloak:
  auth-server-url: ${KEYCLOAK_HOST}
  ssl-required: none
  realm: pm-tool
  resource: user-service
  bearer-only: true
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
